#!/bin/bash
abspath=`realpath "$0"`
plotFolder="${abspath/\/createPlot/}"
resFile=$1
n=$2
resPlotFolder="$resFile/plots"
mkdir -p $resPlotFolder
IFS="," read -r -a fks <<< $("$plotFolder/extractFks" $resFile "${resFile}/fk" $n)
fks_x=${fks[0]}
fks_y=${fks[1]}
gnuplot -c "$plotFolder/makeTrajectoryPlot.gnuplot" $resFile $fks_x $fks_y
