#!/bin/bash
nbArgs=$#
mpcFile=`ls -t -d ../results/mpc* | head -n 1`
fabricFile=`ls -t -d ../results/fabric* | head -n 1`
intervals=1
n=$1
if [[ ( "$#" == 4 ) ]]; then
  mpcFile=$2
  fabricFile=$3
  intervals=$4
fi
if [[ ( "$#" == 3 ) ]]; then
  mpcFile=$2
  fabricFile="${mpcFile/mpc/fabric}"
  intervals=$3
fi
if [[ ( "$#" == 2 ) ]]; then
  intervals=$2
fi
if [ -z "$mpcFile" ];
  then 
    echo "No files found"
    exit
fi
plotFolderMpc="$mpcFile/plots"
plotFolderFabric="$fabricFile/plots"
mkdir -p $plotFolderMpc
mkdir -p $plotFolderFabric
timeStampFabric=${mpcFile:(-15)}
timeStampMpc=${fabricFile:(-15)}
IFS="," read -r -a fks <<< $(./extractFks $mpcFile "${mpcFile}/fk" $n)
fks_x=${fks[0]}
fks_y=${fks[1]}
output=$(./extractFks $fabricFile "${fabricFile}/fk" $n)
gnuplot -c makeTrajectoryPlots.gnuplot $mpcFile $timeStampMpc $fabricFile $timeStampFabric $fks_x $fks_y
gnuplot -c makeSolverTimePlot.gnuplot $mpcFile $fabricFile $intervals
xdg-open "$plotFolderMpc/trajectory.eps"
xdg-open "$plotFolderFabric/trajectory.eps"
cp "$plotFolderMpc/solverTimes.eps" "$plotFolderFabric/"
