#!/bin/bash
abspath=`realpath "$0"`
plotFolder="${abspath/\/createPlot/}"
resFolder=$1
n=$2
resPlotFolder="$resFolder/plots"
mkdir -p $resPlotFolder
. "$plotFolder/extractFks" $resFolder "${resFolder}/fk" $n
pathToMakeTrajectoryPlot="$plotFolder/makeTrajectoryPlot.gnuplot"
gnuplot -c "$plotFolder/makeTrajectoryPlot.gnuplot" $resFolder $n
