#!/bin/bash
nbArgs=$#
mpcFile=`ls -t -d ../results/mpc* | head -n 1`
fabricFile=`ls -t -d ../results/fabric* | head -n 1`
intervals=1
if [[ ( "$#" == 3 ) ]]; then
  mpcFile=$1
  fabricFile=$2
  intervals=$3
fi
if [[ ( "$#" == 1 ) ]]; then
  intervals=$1
fi
# echo $mpcFile
# echo $fabricFile
timeStampFabric=${mpcFile:(-15)}
timeStampMpc=${fabricFile:(-15)}
gnuplot -c makeTrajectoryPlots.gnuplot $mpcFile $timeStampMpc $fabricFile $timeStampFabric
gnuplot -c makeSolverTimePlot.gnuplot $mpcFile $fabricFile $intervals
files=`ls -t | head -n 3`
for file in $files
do
  echo "Attempting to open ${file}"
  xdg-open $file
done
