#!/bin/bash
abspath=`realpath "$0"`
plotFolder="${abspath/\/createPlot/}"
resFile=$1
resPlotFolder="$resFile/plots"
mkdir -p $resPlotFolder
pathToMakeTrajectoryPlot="$plotFolder/makeTrajectoryPlot.gnuplot"
gnuplot -c "$plotFolder/makeTrajectoryPlot.gnuplot" $resFile
